# AWS Lambda
awsLambdaCoreVersion=1.4.0
awsLambdaEventsVersion=3.16.1

# AWS SDK
awsSdkVersion=2.40.2

# AWS CDK
awsCdkVersion=2.231.0
constructsVersion=10.4.3

# JTE Template Engine
jteVersion=3.2.1

# Google API
googleApiClientVersion=2.8.1

# Testing
junitJupiterVersion=5.14.1
junitPlatformVersion=1.14.1
