dependencies {
    implementation project(":zone.realfood.backend")

    implementation platform("software.amazon.awssdk:bom:${awsSdkVersion}")
    implementation "software.amazon.awssdk:dynamodb"
    implementation "software.amazon.awssdk:dynamodb-enhanced"
    implementation "software.amazon.awssdk:regions"
}
