plugins {
  id 'application'
  id 'com.gradleup.shadow' version "9.0.2"
}

application {
  mainClass = 'zone.realfood.Main'
}

dependencies {
  implementation 'software.amazon.awscdk:aws-cdk-lib:2.211.0'
  implementation 'software.constructs:constructs:10.4.2'
}

tasks.shadowJar {
  archiveFileName.set('zone.realfood.cdk.jar')
  mergeServiceFiles()
  manifest { attributes 'Main-Class': 'zone.realfood.Main' }
}

tasks.build.dependsOn tasks.shadowJar
tasks.distZip.dependsOn tasks.shadowJar
tasks.distTar.dependsOn tasks.shadowJar
tasks.startScripts.dependsOn tasks.shadowJar
tasks.startShadowScripts.dependsOn tasks.jar
